name: Deploy Files via Tailscale SSH (Auth Key)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Connect runner to Tailscale network using Auth Key
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_KEY }}
          
      # 2. Configure SSH client and host verification
      - name: Setup SSH
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.DEST_SSH_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEST_HOST }} >> /home/runner/.ssh/known_hosts

      # 3. Sync files directly using rsync
      - name: Sync Files with rsync
        run: |
          rsync -Pavz --delete \
            -e "ssh -i /home/runner/.ssh/id_rsa" \
            mods \
            ${{ secrets.DEST_USER }}@${{ secrets.DEST_HOST }}:/home/isaac/minecraft_datadriven_smp/
            rsync -Pavz --delete \
            -e "ssh -i /home/runner/.ssh/id_rsa" \
            datapacks \
            ${{ secrets.DEST_USER }}@${{ secrets.DEST_HOST }}:/home/isaac/minecraft_datadriven_smp/world/
      
      # 4. Resource pack actions [Part 1 - Zip]
      # 4.1
      - name: RP - Install Zip
        uses: montudor/action-zip@v1
      
      # 4.2
      - name: RP - Make Zip File
        run: zip -qq -r resourcepack.zip assets pack.mcmeta
        working-directory: resourcepack
      
      # 4.3
      - name: RP - Calculate SHA-1
        run: |
          SHA_RESULT=$(sha1sum resourcepack/resourcepack.zip | awk '{print $1}')
          echo "$SHA_RESULT" > resourcepack/resourcepack.sha 

      # 4.4
      - name: RP - Commit & Push Zip
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "138998874+github-actions[bot]@users.noreply.github.com"

          git add resourcepack/resourcepack.zip resourcepack/resourcepack.sha
          git commit -m "Update Resource Pack Zip File"
          git push
      
      

